/**
 * Export a design (§6): PNG-free, all on-device. PDF via expo-print from a to-scale SVG plan (scale
 * bar + north arrow), and GeoJSON / KML / DXF via the system share sheet.
 * County parcel geometry marked "display only" is left out of GIS exports and flagged in the file.
 */
import {
  designToDXF, designToGeoJSON, designToKML, designToSVG, type Areal, type Design, type LocalFrame,
} from '@plotwright/core';
import { File, Paths } from 'expo-file-system';
import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';

export type ExportFormat = 'pdf' | 'geojson' | 'kml' | 'dxf';

export interface ExportContext {
  design: Design;
  boundary: Areal;
  frame: LocalFrame;
  units: 'imperial' | 'metric';
  /** County services marked display-only: keep the parcel line out of GIS exports. */
  boundaryDisplayOnly: boolean;
  parcelName: string;
}

const safe = (s: string) => s.replace(/[^\w.-]+/g, '_').slice(0, 60) || 'plan';

export async function exportDesign(fmt: ExportFormat, ctx: ExportContext): Promise<void> {
  const base = `${safe(ctx.parcelName)}-${safe(ctx.design.name)}`;
  const gisOpts = { includeBoundary: !ctx.boundaryDisplayOnly };
  let uri: string;
  let mime: string;
  if (fmt === 'pdf') {
    const svg = designToSVG(ctx.design, ctx.boundary, ctx.frame, { units: ctx.units, title: `${ctx.parcelName} — ${ctx.design.name}` });
    const html = `<!doctype html><html><head><meta charset="utf-8"><style>
      @page { margin: 12mm; } body { font-family: -apple-system, Roboto, sans-serif; margin: 0; }
      svg { width: 100%; height: auto; } p { font-size: 9pt; color: #555; }
    </style></head><body>${svg}
    <p>Generated by Plotwright on ${new Date().toLocaleDateString()}. Parcel lines from GIS are approximate and are not a legal survey.</p>
    </body></html>`;
    const r = await Print.printToFileAsync({ html });
    uri = r.uri;
    mime = 'application/pdf';
  } else {
    const text =
      fmt === 'geojson' ? designToGeoJSON(ctx.design, ctx.boundary, ctx.frame, gisOpts)
      : fmt === 'kml' ? designToKML(ctx.design, ctx.boundary, ctx.frame, gisOpts)
      : designToDXF(ctx.design, ctx.boundary, ctx.frame, gisOpts);
    const file = new File(Paths.cache, `${base}.${fmt}`);
    if (file.exists) file.delete();
    file.create();
    file.write(text);
    uri = file.uri;
    mime = fmt === 'geojson' ? 'application/geo+json' : fmt === 'kml' ? 'application/vnd.google-earth.kml+xml' : 'application/dxf';
  }
  if (await Sharing.isAvailableAsync()) await Sharing.shareAsync(uri, { mimeType: mime, dialogTitle: `Export ${fmt.toUpperCase()}` });
}
