apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'app.homeground.usersync'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "app.homeground.usersync"
  defaultConfig {
    minSdkVersion 29
  }
}
