apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'

group = 'app.plotwright.shadenative'
version = '0.1.0'

def expoModulesCorePlugin = new File(project(":expo-modules-core").projectDir.absolutePath, "ExpoModulesCorePlugin.gradle")
apply from: expoModulesCorePlugin
applyKotlinExpoModulesCorePlugin()
useCoreDependencies()
useExpoPublishing()

android {
  namespace "app.plotwright.shadenative"
  defaultConfig { minSdkVersion 29 }
}
