/**
 * Bundled plant database, part 2: herbs, fruit, nuts and cover crops. See types.ts for units.
 */
import type { PlantSpec } from './types';

const LAM = 'Lamiaceae', API = 'Apiaceae', AMY = 'Amaryllidaceae', ROS = 'Rosaceae', ERI = 'Ericaceae', VIT = 'Vitaceae',
  MOR = 'Moraceae', EBE = 'Ebenaceae', FAB = 'Fabaceae', POA = 'Poaceae', POL = 'Polygonaceae', AST = 'Asteraceae',
  BET = 'Betulaceae', ANN = 'Annonaceae', GRO = 'Grossulariaceae', ADO = 'Adoxaceae';

export const HERBS: PlantSpec[] = [
  {
    id: 'basil', commonName: 'Basil', scientificName: 'Ocimum basilicum', family: LAM, kind: 'herb', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [60, 75], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 85], days: [5, 10] },
    sowing: { method: 'either', indoorStartWeeks: [6, 4], transplantDays: [14, 28], directSowDays: [14, 28], minSoilF: 65, successionDays: 21 },
    harvestWindowDays: 90, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 12, betweenRows: 18 }, perSquareFoot: 1, heightIn: 18, spreadIn: 12,
    humidityDisease: 'high', diseases: ['basil downy mildew', 'Fusarium wilt'], pests: ['Japanese beetles', 'aphids'], companions: ['tomato', 'pepper-sweet'],
    notes: ['Damaged by nights below 50 °F. Pinch flower buds to keep leaves coming.'],
  },
  {
    id: 'parsley', commonName: 'Parsley', scientificName: 'Petroselinum crispum', family: API, kind: 'herb', lifecycle: 'biennial',
    season: 'cool', frost: 'hardy', heat: 'medium', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [70, 90], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [50, 85], days: [14, 28] },
    sowing: { method: 'either', indoorStartWeeks: [10, 8], transplantDays: [-14, 7], directSowDays: [-21, 7], minSoilF: 45 },
    harvestWindowDays: 150, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 8, betweenRows: 12 }, perSquareFoot: 4, heightIn: 12, spreadIn: 10,
    humidityDisease: 'low', diseases: ['leaf spot'], pests: ['black swallowtail caterpillars'],
  },
  {
    id: 'cilantro', commonName: 'Cilantro / coriander', scientificName: 'Coriandrum sativum', family: API, kind: 'herb', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [45, 70], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [55, 70], days: [7, 14] },
    sowing: { method: 'direct', directSowDays: [-14, 14], minSoilF: 45, fallDaysBeforeFirstFrost: [60, 40], successionDays: 21 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.2, 6.8], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 12 }, perSquareFoot: 9, heightIn: 18, spreadIn: 6,
    humidityDisease: 'low', diseases: ['bacterial leaf spot'], pests: ['aphids'], notes: ['Bolts quickly in heat; seeds are coriander.'],
  },
  {
    id: 'dill', commonName: 'Dill', scientificName: 'Anethum graveolens', family: API, kind: 'herb', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [40, 60], maturityFrom: 'seed',
    germination: { minSoilF: 50, optimalF: [60, 70], days: [7, 21] },
    sowing: { method: 'direct', directSowDays: [0, 21], minSoilF: 50, successionDays: 21 },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [5.5, 6.7], drainage: 'well-drained' },
    spacingIn: { inRow: 12, betweenRows: 18 }, perSquareFoot: 1, heightIn: 36, spreadIn: 12,
    humidityDisease: 'low', diseases: ['leaf spot'], pests: ['aphids', 'black swallowtail caterpillars'], avoidNear: ['carrot'],
  },
  {
    id: 'chives', commonName: 'Chives', scientificName: 'Allium schoenoprasum', family: AMY, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [75, 90], maturityFrom: 'seed',
    germination: { minSoilF: 45, optimalF: [60, 70], days: [7, 14] },
    sowing: { method: 'either', indoorStartWeeks: [8, 6], transplantDays: [-14, 7], directSowDays: [-14, 7], minSoilF: 45 },
    harvestWindowDays: 150, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 8, betweenRows: 12 }, perSquareFoot: 4, heightIn: 12, spreadIn: 8, zones: [3, 9],
    humidityDisease: 'low', diseases: ['rust'], pests: ['onion thrips'],
  },
  {
    id: 'thyme', commonName: 'Thyme', scientificName: 'Thymus vulgaris', family: LAM, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'transplant',
    sowing: { method: 'transplant', indoorStartWeeks: [10, 8], transplantDays: [-7, 14], minSoilF: 50 },
    harvestWindowDays: 150, water: 'low', soil: { pH: [6.0, 8.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 12, betweenRows: 18 }, perSquareFoot: 1, heightIn: 10, spreadIn: 12, zones: [5, 9],
    humidityDisease: 'medium', diseases: ['root rot in wet soil'], pests: ['spider mites'], notes: ['Hates wet feet; lean, gravelly soil is fine.'],
  },
  {
    id: 'oregano', commonName: 'Oregano', scientificName: 'Origanum vulgare', family: LAM, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'transplant',
    sowing: { method: 'transplant', indoorStartWeeks: [8, 6], transplantDays: [-7, 14], minSoilF: 50 },
    harvestWindowDays: 150, water: 'low', soil: { pH: [6.0, 8.0], drainage: 'well-drained' },
    spacingIn: { inRow: 12, betweenRows: 18 }, perSquareFoot: 1, heightIn: 18, spreadIn: 18, zones: [4, 9],
    humidityDisease: 'medium', diseases: ['root rot in wet soil'], pests: ['aphids', 'spider mites'],
  },
  {
    id: 'rosemary', commonName: 'Rosemary', scientificName: 'Salvia rosmarinus', family: LAM, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'transplant',
    sowing: { method: 'plant', transplantDays: [7, 21], minSoilF: 55 },
    harvestWindowDays: 180, water: 'low', soil: { pH: [6.0, 7.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 24, betweenRows: 36 }, heightIn: 36, spreadIn: 36, zones: [7, 10],
    humidityDisease: 'medium', diseases: ['root rot', 'powdery mildew'], pests: ['spider mites'], notes: ['Overwinters outdoors only in zone 7 and warmer; pot it elsewhere.'],
  },
  {
    id: 'sage', commonName: 'Sage', scientificName: 'Salvia officinalis', family: LAM, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'transplant',
    sowing: { method: 'transplant', indoorStartWeeks: [8, 6], transplantDays: [-7, 14], minSoilF: 55 },
    harvestWindowDays: 150, water: 'low', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 24 }, heightIn: 24, spreadIn: 24, zones: [5, 9],
    humidityDisease: 'medium', diseases: ['powdery mildew', 'root rot'], pests: ['spider mites'],
  },
  {
    id: 'mint', commonName: 'Mint', scientificName: 'Mentha spp.', family: LAM, kind: 'herb', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 3, ideal: 6 }, maturityFrom: 'transplant',
    sowing: { method: 'plant', transplantDays: [-14, 14] },
    harvestWindowDays: 150, water: 'high', soil: { pH: [6.0, 7.5], drainage: 'moist' },
    spacingIn: { inRow: 18, betweenRows: 24 }, heightIn: 18, spreadIn: 24, zones: [3, 9],
    humidityDisease: 'low', diseases: ['rust'], pests: ['aphids'], notes: ['Spreads aggressively by runners; grow in a container or a bed of its own.'],
  },
];

export const FRUIT: PlantSpec[] = [
  {
    id: 'strawberry', commonName: 'Strawberry (June-bearing)', scientificName: 'Fragaria × ananassa', family: ROS, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [5.5, 6.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 18, betweenRows: 42 }, perSquareFoot: 1, heightIn: 8, spreadIn: 18, zones: [4, 8],
    humidityDisease: 'high', diseases: ['gray mold (Botrytis)', 'leaf spot', 'Verticillium wilt'], pests: ['slugs', 'tarnished plant bug', 'birds'],
    yieldLb: { per: '10ft-row', range: [5, 10] }, yearsToBearing: [1, 1],
    notes: ['Blossoms are killed by frost: straw or row cover protects early bloom.'],
  },
  {
    id: 'blueberry', commonName: 'Blueberry (highbush)', scientificName: 'Vaccinium corymbosum', family: ERI, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [4.5, 5.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 60, betweenRows: 96 }, heightIn: 72, spreadIn: 60, zones: [4, 7], chillHours: [800, 1000], pollination: 'partly-self',
    humidityDisease: 'medium', diseases: ['mummy berry', 'stem canker'], pests: ['birds', 'spotted wing drosophila'],
    yieldLb: { per: 'plant', range: [5, 10] }, yearsToBearing: [3, 4],
    notes: ['Needs acidic soil (pH 4.5–5.5); plant two varieties for bigger crops.'],
  },
  {
    id: 'raspberry', commonName: 'Raspberry (red)', scientificName: 'Rubus idaeus', family: ROS, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'low', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [5.6, 6.5], drainage: 'well-drained' },
    spacingIn: { inRow: 24, betweenRows: 96 }, heightIn: 60, spreadIn: 24, zones: [3, 8], chillHours: [700, 1000],
    humidityDisease: 'medium', diseases: ['cane blight', 'root rot (Phytophthora)'], pests: ['Japanese beetles', 'spotted wing drosophila'],
    yieldLb: { per: '10ft-row', range: [5, 15] }, yearsToBearing: [1, 2],
    notes: ['Avoid ground where tomatoes, potatoes or peppers grew recently (Verticillium).'],
  },
  {
    id: 'blackberry', commonName: 'Blackberry (thornless)', scientificName: 'Rubus spp.', family: ROS, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [5.5, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 48, betweenRows: 120 }, heightIn: 72, spreadIn: 48, zones: [5, 9], chillHours: [300, 900],
    humidityDisease: 'medium', diseases: ['anthracnose', 'orange rust'], pests: ['spotted wing drosophila', 'Japanese beetles'],
    yieldLb: { per: '10ft-row', range: [10, 20] }, yearsToBearing: [1, 2],
  },
  {
    id: 'grape', commonName: 'Grape (American/hybrid)', scientificName: 'Vitis labrusca and hybrids', family: VIT, kind: 'vine-fruit', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'high', sunHours: { min: 7, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-21, 0] },
    harvestWindowDays: 21, water: 'low', soil: { pH: [5.5, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 96, betweenRows: 108 }, heightIn: 72, spreadIn: 96, zones: [4, 8], chillHours: [100, 500], pollination: 'self',
    humidityDisease: 'high', diseases: ['black rot', 'powdery mildew', 'downy mildew'], pests: ['Japanese beetles', 'grape berry moth', 'birds'],
    yieldLb: { per: 'plant', range: [10, 20] }, yearsToBearing: [3, 3], notes: ['Train on a trellis or arbor; prune hard every winter.'],
  },
  {
    id: 'apple', commonName: 'Apple (semi-dwarf)', scientificName: 'Malus domestica', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 180, betweenRows: 216 }, heightIn: 180, spreadIn: 168, zones: [3, 8], chillHours: [500, 1000], pollination: 'needs-partner',
    humidityDisease: 'high', diseases: ['apple scab', 'cedar-apple rust', 'fire blight'], pests: ['codling moth', 'plum curculio', 'apple maggot'],
    yieldLb: { per: 'plant', range: [150, 300] }, yearsToBearing: [3, 5],
    notes: ['Plant two compatible varieties that bloom together. Disease-resistant varieties save a lot of spraying.'],
  },
  {
    id: 'pear', commonName: 'Pear (European)', scientificName: 'Pyrus communis', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 180, betweenRows: 216 }, heightIn: 216, spreadIn: 168, zones: [4, 8], chillHours: [600, 1000], pollination: 'needs-partner',
    humidityDisease: 'medium', diseases: ['fire blight', 'pear scab'], pests: ['pear psylla', 'codling moth'],
    yieldLb: { per: 'plant', range: [100, 250] }, yearsToBearing: [4, 6],
  },
  {
    id: 'peach', commonName: 'Peach', scientificName: 'Prunus persica', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'high', sunHours: { min: 7, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 180, betweenRows: 216 }, heightIn: 180, spreadIn: 180, zones: [5, 8], chillHours: [400, 1000], pollination: 'self',
    humidityDisease: 'high', diseases: ['brown rot', 'peach leaf curl', 'bacterial spot'], pests: ['plum curculio', 'oriental fruit moth'],
    yieldLb: { per: 'plant', range: [100, 200] }, yearsToBearing: [2, 4],
    notes: ['Blooms early, so spring frosts often take the crop; plant on a slope, not in a low spot.'],
  },
  {
    id: 'plum', commonName: 'Plum (European)', scientificName: 'Prunus domestica', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 180, betweenRows: 216 }, heightIn: 180, spreadIn: 180, zones: [4, 8], chillHours: [700, 1000], pollination: 'partly-self',
    humidityDisease: 'high', diseases: ['black knot', 'brown rot'], pests: ['plum curculio'],
    yieldLb: { per: 'plant', range: [50, 100] }, yearsToBearing: [3, 5],
  },
  {
    id: 'cherry-sour', commonName: 'Tart cherry', scientificName: 'Prunus cerasus', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'low', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 180, betweenRows: 216 }, heightIn: 180, spreadIn: 180, zones: [4, 7], chillHours: [800, 1200], pollination: 'self',
    humidityDisease: 'medium', diseases: ['cherry leaf spot', 'brown rot'], pests: ['cherry fruit fly', 'birds'],
    yieldLb: { per: 'plant', range: [30, 60] }, yearsToBearing: [3, 5],
  },
  {
    id: 'cherry-sweet', commonName: 'Sweet cherry', scientificName: 'Prunus avium', family: ROS, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'hardy', heat: 'low', sunHours: { min: 7, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 240, betweenRows: 264 }, heightIn: 240, spreadIn: 240, zones: [5, 7], chillHours: [800, 1200], pollination: 'needs-partner',
    humidityDisease: 'high', diseases: ['brown rot', 'bacterial canker', 'fruit cracking in rain'], pests: ['birds', 'cherry fruit fly'],
    yieldLb: { per: 'plant', range: [30, 75] }, yearsToBearing: [4, 7],
  },
  {
    id: 'fig', commonName: 'Fig', scientificName: 'Ficus carica', family: MOR, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'half-hardy', heat: 'high', sunHours: { min: 7, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', transplantDays: [0, 21] },
    harvestWindowDays: 45, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 144, betweenRows: 180 }, heightIn: 144, spreadIn: 144, zones: [7, 10], chillHours: [100, 300], pollination: 'self',
    humidityDisease: 'low', diseases: ['fig rust', 'root-knot nematodes'], pests: ['birds', 'squirrels'],
    yieldLb: { per: 'plant', range: [20, 60] }, yearsToBearing: [2, 3],
    notes: ['Hardy types can resprout from roots in zone 6 with winter protection.'],
  },
  {
    id: 'persimmon-american', commonName: 'American persimmon', scientificName: 'Diospyros virginiana', family: EBE, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'high', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 45, water: 'low', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 240, betweenRows: 240 }, heightIn: 360, spreadIn: 240, zones: [4, 9], chillHours: [200, 400], pollination: 'needs-partner',
    humidityDisease: 'low', diseases: ['persimmon wilt'], pests: ['deer', 'raccoons'],
    yieldLb: { per: 'plant', range: [20, 50] }, yearsToBearing: [3, 6], notes: ['Native tree; fruit is astringent until very soft.'],
  },
  {
    id: 'pawpaw', commonName: 'Pawpaw', scientificName: 'Asimina triloba', family: ANN, kind: 'fruit-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 5, ideal: 7 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-14, 14] },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [5.5, 7.0], drainage: 'moist' },
    spacingIn: { inRow: 96, betweenRows: 144 }, heightIn: 240, spreadIn: 144, zones: [5, 8], chillHours: [400, 500], pollination: 'needs-partner',
    humidityDisease: 'low', diseases: ['few serious'], pests: ['zebra swallowtail caterpillars (harmless)'],
    yieldLb: { per: 'plant', range: [25, 50] }, yearsToBearing: [4, 6], notes: ['Young trees need some shade their first year or two.'],
  },
  {
    id: 'hazelnut', commonName: 'Hazelnut', scientificName: 'Corylus americana × avellana', family: BET, kind: 'nut-tree', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 72, betweenRows: 144 }, heightIn: 144, spreadIn: 120, zones: [4, 8], chillHours: [800, 1200], pollination: 'wind',
    humidityDisease: 'medium', diseases: ['eastern filbert blight'], pests: ['squirrels', 'filbert weevil'],
    yieldLb: { per: 'plant', range: [5, 15] }, yearsToBearing: [3, 5], notes: ['Plant blight-resistant hybrids in the East; needs two varieties.'],
  },
  {
    id: 'currant', commonName: 'Currant (red/black)', scientificName: 'Ribes spp.', family: GRO, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [5.5, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 48, betweenRows: 96 }, heightIn: 48, spreadIn: 48, zones: [3, 6], chillHours: [800, 1600], pollination: 'self',
    humidityDisease: 'medium', diseases: ['powdery mildew', 'white pine blister rust (host)'], pests: ['currant sawfly', 'aphids'],
    yieldLb: { per: 'plant', range: [4, 8] }, yearsToBearing: [2, 3], notes: ['Tolerates part shade. Some areas restrict black currants; check local rules.'],
  },
  {
    id: 'elderberry', commonName: 'Elderberry (American)', scientificName: 'Sambucus canadensis', family: ADO, kind: 'berry', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'high', sunHours: { min: 5, ideal: 7 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-14, 14] },
    harvestWindowDays: 21, water: 'high', soil: { pH: [5.5, 7.5], drainage: 'tolerates-wet' },
    spacingIn: { inRow: 72, betweenRows: 144 }, heightIn: 120, spreadIn: 96, zones: [3, 9], pollination: 'partly-self',
    humidityDisease: 'low', diseases: ['cankers'], pests: ['birds', 'spotted wing drosophila'],
    yieldLb: { per: 'plant', range: [10, 15] }, yearsToBearing: [1, 2], notes: ['Raw berries, stems and leaves are toxic; cook the fruit.'],
  },
];

export const COVER_CROPS: PlantSpec[] = [
  {
    id: 'winter-rye', commonName: 'Cereal (winter) rye', scientificName: 'Secale cereale', family: POA, kind: 'cover-crop', lifecycle: 'annual',
    season: 'cool', frost: 'very-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    germination: { minSoilF: 34, optimalF: [50, 75], days: [5, 10] },
    sowing: { method: 'direct', fallDaysBeforeFirstFrost: [21, -28], minSoilF: 34 },
    water: 'low', soil: { pH: [5.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 1, betweenRows: 7 }, heightIn: 48, spreadIn: 4,
    humidityDisease: 'low', diseases: [], pests: [], notes: ['The hardiest fall cover; turn under or cut 3 weeks before planting the bed.'],
  },
  {
    id: 'crimson-clover', commonName: 'Crimson clover', scientificName: 'Trifolium incarnatum', family: FAB, kind: 'cover-crop', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 5, ideal: 6 },
    germination: { minSoilF: 40, optimalF: [50, 75], days: [5, 10] },
    sowing: { method: 'direct', fallDaysBeforeFirstFrost: [56, 42], minSoilF: 40 },
    water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 1, betweenRows: 6 }, heightIn: 18, spreadIn: 6, zones: [6, 9],
    humidityDisease: 'low', diseases: [], pests: [], notes: ['Fixes nitrogen and feeds pollinators; winter-kills north of zone 6.'],
  },
  {
    id: 'buckwheat', commonName: 'Buckwheat', scientificName: 'Fagopyrum esculentum', family: POL, kind: 'cover-crop', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 5, ideal: 6 },
    germination: { minSoilF: 50, optimalF: [65, 85], days: [3, 5] },
    sowing: { method: 'direct', directSowDays: [7, 75], minSoilF: 50 },
    water: 'low', soil: { pH: [5.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 1, betweenRows: 7 }, heightIn: 36, spreadIn: 6,
    humidityDisease: 'low', diseases: [], pests: [], notes: ['Smothers weeds in 6–8 weeks; cut before seeds set.'],
  },
  {
    id: 'sunflower', commonName: 'Sunflower', scientificName: 'Helianthus annuus', family: AST, kind: 'flower', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [70, 100], maturityFrom: 'seed',
    germination: { minSoilF: 50, optimalF: [70, 85], days: [7, 10] },
    sowing: { method: 'direct', directSowDays: [0, 42], minSoilF: 55, successionDays: 21 },
    harvestWindowDays: 21, water: 'low', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 30 }, heightIn: 96, spreadIn: 24,
    humidityDisease: 'low', diseases: ['downy mildew', 'rust'], pests: ['birds', 'sunflower moth'],
    notes: ['Tall varieties cast a long shadow; plant on the north side of the garden.'],
  },
];
