/**
 * Bundled plant database, part 1: vegetables. See types.ts for units and caveats.
 * Timing is relative to the parcel's median last spring / first fall frost (computed per parcel).
 */
import type { PlantSpec } from './types';

const SOL = 'Solanaceae', BRA = 'Brassicaceae', CUC = 'Cucurbitaceae', FAB = 'Fabaceae', AMA = 'Amaranthaceae',
  API = 'Apiaceae', AMY = 'Amaryllidaceae', AST = 'Asteraceae', POA = 'Poaceae', MAL = 'Malvaceae', CON = 'Convolvulaceae',
  ASP = 'Asparagaceae', POL = 'Polygonaceae';

const BRASSICA_PESTS = ['cabbage worms', 'flea beetles', 'aphids', 'cabbage root maggot'];
const BRASSICA_DISEASES = ['black rot', 'clubroot', 'downy mildew'];
const CUCURBIT_PESTS = ['cucumber beetles', 'squash bugs', 'squash vine borer'];
const CUKE_MELON_PESTS = ['cucumber beetles', 'squash bugs', 'aphids'];
const CUCURBIT_DISEASES = ['powdery mildew', 'downy mildew', 'bacterial wilt'];

export const VEGETABLES: PlantSpec[] = [
  {
    id: 'tomato', commonName: 'Tomato', scientificName: 'Solanum lycopersicum', family: SOL, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [55, 85], maturityFrom: 'transplant',
    germination: { minSoilF: 50, optimalF: [70, 85], days: [6, 14] },
    sowing: { method: 'transplant', indoorStartWeeks: [8, 6], transplantDays: [7, 21], minSoilF: 60 },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [6.2, 6.8], drainage: 'well-drained', textures: ['loamy', 'sandy'] },
    spacingIn: { inRow: 24, betweenRows: 48 }, heightIn: 60, spreadIn: 24,
    humidityDisease: 'high', diseases: ['early blight', 'Septoria leaf spot', 'late blight', 'blossom-end rot (calcium/watering)'],
    pests: ['tomato hornworm', 'aphids', 'stink bugs'], companions: ['basil', 'carrot', 'onion'], avoidNear: ['potato', 'corn'],
    yieldLb: { per: '10ft-row', range: [15, 45] },
    notes: ['Stake or cage; indeterminate varieties keep growing and producing until frost.'],
  },
  {
    id: 'pepper-sweet', commonName: 'Sweet pepper', scientificName: 'Capsicum annuum', family: SOL, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [60, 90], maturityFrom: 'transplant',
    germination: { minSoilF: 60, optimalF: [75, 85], days: [8, 20] },
    sowing: { method: 'transplant', indoorStartWeeks: [10, 8], transplantDays: [14, 28], minSoilF: 65 },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [6.0, 6.8], drainage: 'well-drained', textures: ['loamy', 'sandy'] },
    spacingIn: { inRow: 18, betweenRows: 30 }, heightIn: 30, spreadIn: 18,
    humidityDisease: 'medium', diseases: ['bacterial leaf spot', 'Phytophthora blight', 'blossom-end rot'],
    pests: ['aphids', 'pepper maggot', 'European corn borer'], companions: ['basil', 'onion'],
    yieldLb: { per: '10ft-row', range: [5, 10] },
    notes: ['Night temperatures below 55 °F slow growth; wait for warm soil.'],
  },
  {
    id: 'pepper-hot', commonName: 'Hot pepper', scientificName: 'Capsicum spp. (mostly C. annuum)', family: SOL, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [65, 100], maturityFrom: 'transplant',
    germination: { minSoilF: 60, optimalF: [75, 85], days: [8, 25] },
    sowing: { method: 'transplant', indoorStartWeeks: [10, 8], transplantDays: [14, 28], minSoilF: 65 },
    harvestWindowDays: 70, water: 'medium', soil: { pH: [6.0, 6.8], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 30 }, heightIn: 30, spreadIn: 18,
    humidityDisease: 'medium', diseases: ['bacterial leaf spot', 'Phytophthora blight'], pests: ['aphids', 'pepper weevil (South)'],
    yieldLb: { per: '10ft-row', range: [3, 8] },
  },
  {
    id: 'eggplant', commonName: 'Eggplant', scientificName: 'Solanum melongena', family: SOL, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [60, 80], maturityFrom: 'transplant',
    germination: { minSoilF: 60, optimalF: [75, 85], days: [7, 14] },
    sowing: { method: 'transplant', indoorStartWeeks: [10, 8], transplantDays: [14, 28], minSoilF: 65 },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [5.8, 6.8], drainage: 'well-drained' },
    spacingIn: { inRow: 24, betweenRows: 36 }, heightIn: 36, spreadIn: 24,
    humidityDisease: 'medium', diseases: ['Verticillium wilt', 'Phomopsis blight'], pests: ['flea beetles', 'Colorado potato beetle'],
    yieldLb: { per: '10ft-row', range: [10, 20] },
  },
  {
    id: 'potato', commonName: 'Potato', scientificName: 'Solanum tuberosum', family: SOL, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [70, 120], maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, -7], minSoilF: 45 },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [5.0, 6.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 12, betweenRows: 30 }, heightIn: 24, spreadIn: 18,
    humidityDisease: 'high', diseases: ['late blight', 'early blight', 'scab (high pH)'], pests: ['Colorado potato beetle', 'wireworms', 'leafhoppers'],
    avoidNear: ['tomato'], yieldLb: { per: '10ft-row', range: [10, 20] },
    notes: ['Plant certified seed potatoes; foliage is killed by frost but tubers are safe underground.'],
  },
  {
    id: 'sweet-potato', commonName: 'Sweet potato', scientificName: 'Ipomoea batatas', family: CON, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [90, 120], maturityFrom: 'transplant',
    sowing: { method: 'transplant', transplantDays: [21, 35], minSoilF: 65 },
    harvestWindowDays: 21, water: 'low', soil: { pH: [5.5, 6.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 15, betweenRows: 36 }, heightIn: 12, spreadIn: 48,
    humidityDisease: 'low', diseases: ['black rot', 'scurf'], pests: ['sweet potato weevil (South)', 'wireworms'],
    yieldLb: { per: '10ft-row', range: [8, 15] },
    notes: ['Grown from rooted slips; needs a long, warm season. Cure after harvest.'],
  },
  {
    id: 'lettuce', commonName: 'Lettuce', scientificName: 'Lactuca sativa', family: AST, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [30, 70], maturityFrom: 'seed',
    germination: { minSoilF: 35, optimalF: [55, 70], days: [4, 10] },
    sowing: { method: 'either', indoorStartWeeks: [6, 4], transplantDays: [-21, 0], directSowDays: [-28, 14], minSoilF: 40, fallDaysBeforeFirstFrost: [60, 40], successionDays: 14 },
    harvestWindowDays: 21, water: 'high', soil: { pH: [6.0, 7.0], drainage: 'moist' },
    spacingIn: { inRow: 8, betweenRows: 12 }, perSquareFoot: 4, heightIn: 8, spreadIn: 10,
    humidityDisease: 'medium', diseases: ['downy mildew', 'bottom rot'], pests: ['aphids', 'slugs'],
    companions: ['carrot', 'radish'], yieldLb: { per: '10ft-row', range: [4, 10] },
    notes: ['Bolts and turns bitter in heat; afternoon shade extends the season.'],
  },
  {
    id: 'spinach', commonName: 'Spinach', scientificName: 'Spinacia oleracea', family: AMA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'very-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [37, 50], maturityFrom: 'seed',
    germination: { minSoilF: 35, optimalF: [45, 70], days: [6, 14] },
    sowing: { method: 'direct', directSowDays: [-42, -14], minSoilF: 35, fallDaysBeforeFirstFrost: [50, 30], successionDays: 14 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.5, 7.5], drainage: 'moist' },
    spacingIn: { inRow: 4, betweenRows: 12 }, perSquareFoot: 9, heightIn: 8, spreadIn: 8,
    humidityDisease: 'medium', diseases: ['downy mildew'], pests: ['leafminers', 'aphids'],
    yieldLb: { per: '10ft-row', range: [4, 6] },
    notes: ['Bolts as days lengthen; sow early spring or late summer.'],
  },
  {
    id: 'kale', commonName: 'Kale', scientificName: 'Brassica oleracea (Acephala group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'very-hardy', heat: 'medium', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [50, 65], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [5, 10] },
    sowing: { method: 'either', indoorStartWeeks: [6, 4], transplantDays: [-28, -7], directSowDays: [-28, 0], minSoilF: 40, fallDaysBeforeFirstFrost: [90, 60] },
    harvestWindowDays: 120, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 12, betweenRows: 24 }, perSquareFoot: 1, heightIn: 24, spreadIn: 18,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 10] },
    notes: ['Flavor sweetens after frost; harvest outer leaves all season.'],
  },
  {
    id: 'collards', commonName: 'Collards', scientificName: 'Brassica oleracea (Viridis group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'very-hardy', heat: 'high', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [55, 80], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [5, 10] },
    sowing: { method: 'either', indoorStartWeeks: [7, 5], transplantDays: [-28, 0], directSowDays: [-28, 0], minSoilF: 40, fallDaysBeforeFirstFrost: [90, 60] },
    harvestWindowDays: 120, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 30 }, heightIn: 30, spreadIn: 24,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [8, 15] },
  },
  {
    id: 'cabbage', commonName: 'Cabbage', scientificName: 'Brassica oleracea (Capitata group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [60, 100], maturityFrom: 'transplant',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 10] },
    sowing: { method: 'transplant', indoorStartWeeks: [7, 5], transplantDays: [-28, -14], minSoilF: 45, fallDaysBeforeFirstFrost: [100, 80] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 30 }, perSquareFoot: 1, heightIn: 18, spreadIn: 24,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [10, 20] },
  },
  {
    id: 'broccoli', commonName: 'Broccoli', scientificName: 'Brassica oleracea (Italica group)', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [55, 85], maturityFrom: 'transplant',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 10] },
    sowing: { method: 'transplant', indoorStartWeeks: [7, 5], transplantDays: [-21, -7], minSoilF: 45, fallDaysBeforeFirstFrost: [100, 80] },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 18, betweenRows: 30 }, perSquareFoot: 1, heightIn: 24, spreadIn: 18,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 10] },
    notes: ['Side shoots keep coming after the main head is cut.'],
  },
  {
    id: 'cauliflower', commonName: 'Cauliflower', scientificName: 'Brassica oleracea (Botrytis group)', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [55, 80], maturityFrom: 'transplant',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 10] },
    sowing: { method: 'transplant', indoorStartWeeks: [7, 5], transplantDays: [-14, 0], minSoilF: 45, fallDaysBeforeFirstFrost: [100, 80] },
    harvestWindowDays: 14, water: 'high', soil: { pH: [6.0, 7.0], drainage: 'moist' },
    spacingIn: { inRow: 18, betweenRows: 30 }, perSquareFoot: 1, heightIn: 24, spreadIn: 24,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 10] },
    notes: ['The fussiest brassica: stress from heat, cold or drought makes small "buttoned" heads.'],
  },
  {
    id: 'brussels-sprouts', commonName: 'Brussels sprouts', scientificName: 'Brassica oleracea (Gemmifera group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'very-hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [90, 110], maturityFrom: 'transplant',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 10] },
    sowing: { method: 'transplant', indoorStartWeeks: [8, 6], transplantDays: [-14, 14], minSoilF: 45, fallDaysBeforeFirstFrost: [130, 110] },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 24, betweenRows: 30 }, heightIn: 36, spreadIn: 24,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [4, 8] },
    notes: ['Best harvested after light frosts in fall.'],
  },
  {
    id: 'kohlrabi', commonName: 'Kohlrabi', scientificName: 'Brassica oleracea (Gongylodes group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [45, 60], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 10] },
    sowing: { method: 'direct', directSowDays: [-28, -7], minSoilF: 40, fallDaysBeforeFirstFrost: [70, 50], successionDays: 14 },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 18 }, perSquareFoot: 4, heightIn: 12, spreadIn: 10,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 8] },
  },
  {
    id: 'swiss-chard', commonName: 'Swiss chard', scientificName: 'Beta vulgaris (Cicla group)', family: AMA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'half-hardy', heat: 'high', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [50, 60], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [50, 85], days: [5, 14] },
    sowing: { method: 'direct', directSowDays: [-14, 14], minSoilF: 45, fallDaysBeforeFirstFrost: [70, 50] },
    harvestWindowDays: 120, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 10, betweenRows: 18 }, perSquareFoot: 4, heightIn: 20, spreadIn: 12,
    humidityDisease: 'low', diseases: ['Cercospora leaf spot'], pests: ['leafminers', 'aphids'], yieldLb: { per: '10ft-row', range: [8, 15] },
  },
  {
    id: 'beet', commonName: 'Beet', scientificName: 'Beta vulgaris', family: AMA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'half-hardy', heat: 'medium', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [50, 70], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [50, 85], days: [5, 14] },
    sowing: { method: 'direct', directSowDays: [-28, 0], minSoilF: 45, fallDaysBeforeFirstFrost: [70, 50], successionDays: 21 },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 3, betweenRows: 15 }, perSquareFoot: 9, heightIn: 12, spreadIn: 6,
    humidityDisease: 'low', diseases: ['Cercospora leaf spot', 'scab'], pests: ['leafminers'], yieldLb: { per: '10ft-row', range: [8, 15] },
  },
  {
    id: 'carrot', commonName: 'Carrot', scientificName: 'Daucus carota subsp. sativus', family: API, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'half-hardy', heat: 'medium', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [55, 80], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [55, 80], days: [10, 21] },
    sowing: { method: 'direct', directSowDays: [-21, 14], minSoilF: 45, fallDaysBeforeFirstFrost: [90, 70], successionDays: 21 },
    harvestWindowDays: 45, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 2, betweenRows: 12 }, perSquareFoot: 16, heightIn: 12, spreadIn: 4,
    humidityDisease: 'low', diseases: ['Alternaria leaf blight', 'root-knot nematodes'], pests: ['carrot rust fly', 'wireworms'],
    companions: ['onion', 'lettuce', 'tomato'], yieldLb: { per: '10ft-row', range: [7, 12] },
    notes: ['Keep the seedbed moist until sprouting; heavy clay gives stubby or forked roots.'],
  },
  {
    id: 'radish', commonName: 'Radish', scientificName: 'Raphanus sativus', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [22, 35], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [55, 85], days: [3, 7] },
    sowing: { method: 'direct', directSowDays: [-35, 0], minSoilF: 40, fallDaysBeforeFirstFrost: [45, 25], successionDays: 10 },
    harvestWindowDays: 7, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 2, betweenRows: 8 }, perSquareFoot: 16, heightIn: 6, spreadIn: 3,
    humidityDisease: 'low', diseases: ['clubroot'], pests: ['flea beetles', 'root maggots'], yieldLb: { per: '10ft-row', range: [3, 5] },
  },
  {
    id: 'turnip', commonName: 'Turnip', scientificName: 'Brassica rapa (Rapifera group)', family: BRA, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [40, 60], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [3, 10] },
    sowing: { method: 'direct', directSowDays: [-28, 0], minSoilF: 40, fallDaysBeforeFirstFrost: [70, 50] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 4, betweenRows: 15 }, perSquareFoot: 9, heightIn: 12, spreadIn: 8,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 10] },
  },
  {
    id: 'parsnip', commonName: 'Parsnip', scientificName: 'Pastinaca sativa', family: API, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'very-hardy', heat: 'low', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [100, 130], maturityFrom: 'seed',
    germination: { minSoilF: 35, optimalF: [50, 70], days: [15, 28] },
    sowing: { method: 'direct', directSowDays: [-21, 0], minSoilF: 40 },
    harvestWindowDays: 90, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 4, betweenRows: 18 }, perSquareFoot: 9, heightIn: 18, spreadIn: 6,
    humidityDisease: 'low', diseases: ['canker'], pests: ['carrot rust fly'], yieldLb: { per: '10ft-row', range: [5, 10] },
    notes: ['Use fresh seed; roots sweeten after frost and can overwinter in the ground.'],
  },
  {
    id: 'onion', commonName: 'Onion (bulb)', scientificName: 'Allium cepa', family: AMY, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [90, 120], maturityFrom: 'planting',
    germination: { minSoilF: 35, optimalF: [50, 85], days: [7, 14] },
    sowing: { method: 'either', indoorStartWeeks: [12, 10], transplantDays: [-35, -14], directSowDays: [-35, -14], minSoilF: 40 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 4, betweenRows: 12 }, perSquareFoot: 9, heightIn: 18, spreadIn: 4,
    humidityDisease: 'medium', diseases: ['downy mildew', 'neck rot'], pests: ['onion thrips', 'onion maggot'],
    companions: ['carrot', 'tomato'], avoidNear: ['pea', 'bean-bush', 'bean-pole'], yieldLb: { per: '10ft-row', range: [7, 12] },
    notes: ['Bulbing depends on day length: long-day types in the North, short-day in the South.'],
  },
  {
    id: 'garlic', commonName: 'Garlic', scientificName: 'Allium sativum', family: AMY, kind: 'vegetable', lifecycle: 'perennial',
    season: 'cool', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [240, 270], maturityFrom: 'planting',
    sowing: { method: 'plant', fallDaysBeforeFirstFrost: [0, -28] },
    harvestWindowDays: 14, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 12 }, perSquareFoot: 4, heightIn: 24, spreadIn: 6,
    humidityDisease: 'low', diseases: ['white rot', 'rust'], pests: ['onion thrips'], yieldLb: { per: '10ft-row', range: [3, 6] },
    notes: ['Plant cloves in fall, from the first frost to about four weeks after, and harvest the next summer.'],
  },
  {
    id: 'leek', commonName: 'Leek', scientificName: 'Allium ampeloprasum (Porrum group)', family: AMY, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [100, 130], maturityFrom: 'transplant',
    germination: { minSoilF: 35, optimalF: [50, 80], days: [7, 14] },
    sowing: { method: 'transplant', indoorStartWeeks: [12, 10], transplantDays: [-21, 0], minSoilF: 40 },
    harvestWindowDays: 90, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 18 }, perSquareFoot: 4, heightIn: 24, spreadIn: 6,
    humidityDisease: 'low', diseases: ['rust', 'purple blotch'], pests: ['onion thrips', 'leek moth'], yieldLb: { per: '10ft-row', range: [8, 12] },
  },
  {
    id: 'scallion', commonName: 'Green onion', scientificName: 'Allium fistulosum', family: AMY, kind: 'vegetable', lifecycle: 'perennial',
    season: 'cool', frost: 'very-hardy', heat: 'medium', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [60, 70], maturityFrom: 'seed',
    germination: { minSoilF: 35, optimalF: [50, 85], days: [7, 14] },
    sowing: { method: 'direct', directSowDays: [-28, 14], minSoilF: 40, successionDays: 21 },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 2, betweenRows: 12 }, perSquareFoot: 16, heightIn: 16, spreadIn: 2,
    humidityDisease: 'low', diseases: ['downy mildew'], pests: ['onion thrips'], yieldLb: { per: '10ft-row', range: [3, 6] },
  },
  {
    id: 'pea', commonName: 'Garden pea', scientificName: 'Pisum sativum', family: FAB, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [55, 70], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [55, 75], days: [7, 14] },
    sowing: { method: 'direct', directSowDays: [-42, -21], minSoilF: 40, fallDaysBeforeFirstFrost: [80, 60] },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 2, betweenRows: 24 }, perSquareFoot: 8, heightIn: 48, spreadIn: 8,
    humidityDisease: 'medium', diseases: ['powdery mildew', 'root rot'], pests: ['aphids', 'pea weevil'],
    avoidNear: ['onion', 'garlic'], yieldLb: { per: '10ft-row', range: [2, 4] },
    notes: ['Fixes nitrogen; most varieties need a trellis. Stops producing in hot weather.'],
  },
  {
    id: 'bean-bush', commonName: 'Snap bean (bush)', scientificName: 'Phaseolus vulgaris', family: FAB, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [50, 60], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 85], days: [6, 10] },
    sowing: { method: 'direct', directSowDays: [7, 60], minSoilF: 60, fallDaysBeforeFirstFrost: [75, 60], successionDays: 14 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 4, betweenRows: 24 }, perSquareFoot: 9, heightIn: 20, spreadIn: 12,
    humidityDisease: 'medium', diseases: ['bean rust', 'anthracnose', 'white mold'], pests: ['Mexican bean beetle', 'aphids'],
    avoidNear: ['onion', 'garlic'], yieldLb: { per: '10ft-row', range: [5, 10] },
  },
  {
    id: 'bean-pole', commonName: 'Snap bean (pole)', scientificName: 'Phaseolus vulgaris', family: FAB, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [60, 70], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 85], days: [6, 10] },
    sowing: { method: 'direct', directSowDays: [7, 30], minSoilF: 60 },
    harvestWindowDays: 60, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 36 }, perSquareFoot: 8, heightIn: 96, spreadIn: 12,
    humidityDisease: 'medium', diseases: ['bean rust', 'anthracnose'], pests: ['Mexican bean beetle'],
    companions: ['corn', 'squash-winter'], avoidNear: ['onion'], yieldLb: { per: '10ft-row', range: [8, 15] },
    notes: ['Needs a 6–8 ft trellis; shades anything on its north side.'],
  },
  {
    id: 'bean-dry', commonName: 'Dry bean', scientificName: 'Phaseolus vulgaris', family: FAB, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [85, 105], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 85], days: [6, 10] },
    sowing: { method: 'direct', directSowDays: [7, 28], minSoilF: 60 },
    harvestWindowDays: 14, water: 'low', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 4, betweenRows: 24 }, heightIn: 20, spreadIn: 12,
    humidityDisease: 'medium', diseases: ['white mold', 'anthracnose'], pests: ['Mexican bean beetle'], yieldLb: { per: '10ft-row', range: [1, 2] },
    notes: ['A storable protein crop: harvest when pods are dry and rattle.'],
  },
  {
    id: 'bean-lima', commonName: 'Lima bean', scientificName: 'Phaseolus lunatus', family: FAB, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [65, 90], maturityFrom: 'seed',
    germination: { minSoilF: 65, optimalF: [75, 85], days: [7, 14] },
    sowing: { method: 'direct', directSowDays: [14, 35], minSoilF: 65 },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 30 }, heightIn: 24, spreadIn: 12,
    humidityDisease: 'medium', diseases: ['downy mildew'], pests: ['Mexican bean beetle', 'stink bugs'], yieldLb: { per: '10ft-row', range: [2, 5] },
  },
  {
    id: 'cucumber', commonName: 'Cucumber', scientificName: 'Cucumis sativus', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [50, 70], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 95], days: [3, 10] },
    sowing: { method: 'either', indoorStartWeeks: [4, 2], transplantDays: [14, 28], directSowDays: [14, 42], minSoilF: 65, successionDays: 28 },
    harvestWindowDays: 45, water: 'high', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 12, betweenRows: 48 }, perSquareFoot: 2, heightIn: 72, spreadIn: 24,
    humidityDisease: 'high', diseases: CUCURBIT_DISEASES, pests: CUKE_MELON_PESTS, yieldLb: { per: '10ft-row', range: [10, 15] },
    notes: ['Trellising saves space and dries the leaves, reducing disease.'],
  },
  {
    id: 'squash-summer', commonName: 'Summer squash / zucchini', scientificName: 'Cucurbita pepo', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [45, 60], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 95], days: [3, 10] },
    sowing: { method: 'either', indoorStartWeeks: [4, 2], transplantDays: [14, 21], directSowDays: [14, 42], minSoilF: 65, successionDays: 35 },
    harvestWindowDays: 60, water: 'high', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 36, betweenRows: 48 }, heightIn: 30, spreadIn: 48,
    humidityDisease: 'high', diseases: CUCURBIT_DISEASES, pests: CUCURBIT_PESTS, yieldLb: { per: '10ft-row', range: [15, 30] },
  },
  {
    id: 'squash-winter', commonName: 'Winter squash', scientificName: 'Cucurbita maxima / moschata / pepo', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [80, 110], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 95], days: [3, 10] },
    sowing: { method: 'either', indoorStartWeeks: [4, 2], transplantDays: [14, 21], directSowDays: [14, 28], minSoilF: 65 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 48, betweenRows: 72 }, heightIn: 24, spreadIn: 96,
    humidityDisease: 'high', diseases: CUCURBIT_DISEASES, pests: CUCURBIT_PESTS, companions: ['corn', 'bean-pole'],
    yieldLb: { per: '10ft-row', range: [15, 30] }, notes: ['Vines sprawl 10 ft or more. Cure and store for months.'],
  },
  {
    id: 'pumpkin', commonName: 'Pumpkin', scientificName: 'Cucurbita pepo / maxima', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'medium', sunHours: { min: 6, ideal: 8 },
    daysToMaturity: [90, 120], maturityFrom: 'seed',
    germination: { minSoilF: 60, optimalF: [70, 95], days: [3, 10] },
    sowing: { method: 'direct', directSowDays: [14, 28], minSoilF: 65 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 60, betweenRows: 96 }, heightIn: 24, spreadIn: 120,
    humidityDisease: 'high', diseases: CUCURBIT_DISEASES, pests: CUCURBIT_PESTS, yieldLb: { per: '10ft-row', range: [15, 40] },
  },
  {
    id: 'watermelon', commonName: 'Watermelon', scientificName: 'Citrullus lanatus', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 10 },
    daysToMaturity: [70, 95], maturityFrom: 'seed',
    germination: { minSoilF: 65, optimalF: [75, 95], days: [3, 12] },
    sowing: { method: 'either', indoorStartWeeks: [4, 2], transplantDays: [14, 28], directSowDays: [14, 28], minSoilF: 70 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 36, betweenRows: 72 }, heightIn: 18, spreadIn: 96,
    humidityDisease: 'high', diseases: ['anthracnose', 'Fusarium wilt', 'powdery mildew'], pests: CUKE_MELON_PESTS,
    yieldLb: { per: '10ft-row', range: [15, 40] }, notes: ['Needs heat: black plastic mulch helps in short-season areas.'],
  },
  {
    id: 'muskmelon', commonName: 'Cantaloupe / muskmelon', scientificName: 'Cucumis melo', family: CUC, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 10 },
    daysToMaturity: [70, 90], maturityFrom: 'seed',
    germination: { minSoilF: 65, optimalF: [75, 95], days: [3, 10] },
    sowing: { method: 'either', indoorStartWeeks: [4, 2], transplantDays: [14, 28], directSowDays: [14, 28], minSoilF: 70 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 24, betweenRows: 60 }, heightIn: 12, spreadIn: 72,
    humidityDisease: 'high', diseases: CUCURBIT_DISEASES, pests: CUKE_MELON_PESTS, yieldLb: { per: '10ft-row', range: [10, 20] },
  },
  {
    id: 'corn', commonName: 'Sweet corn', scientificName: 'Zea mays', family: POA, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 10 },
    daysToMaturity: [65, 90], maturityFrom: 'seed', gddToMaturity: 1500, gddBaseF: 50,
    germination: { minSoilF: 50, optimalF: [60, 95], days: [5, 10] },
    sowing: { method: 'direct', directSowDays: [7, 42], minSoilF: 60, successionDays: 14 },
    harvestWindowDays: 7, water: 'high', soil: { pH: [6.0, 6.8], drainage: 'well-drained' },
    spacingIn: { inRow: 10, betweenRows: 30 }, heightIn: 84, spreadIn: 18, pollination: 'wind',
    humidityDisease: 'medium', diseases: ['common rust', 'smut'], pests: ['corn earworm', 'European corn borer', 'raccoons'],
    companions: ['bean-pole', 'squash-winter'], avoidNear: ['tomato'], yieldLb: { per: '10ft-row', range: [7, 10] },
    notes: ['Plant in blocks of at least four rows for pollination; tall stalks shade their north side.'],
  },
  {
    id: 'okra', commonName: 'Okra', scientificName: 'Abelmoschus esculentus', family: MAL, kind: 'vegetable', lifecycle: 'annual',
    season: 'warm', frost: 'tender', heat: 'high', sunHours: { min: 6, ideal: 10 },
    daysToMaturity: [50, 65], maturityFrom: 'seed',
    germination: { minSoilF: 65, optimalF: [75, 95], days: [5, 14] },
    sowing: { method: 'direct', directSowDays: [21, 42], minSoilF: 65 },
    harvestWindowDays: 60, water: 'low', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 15, betweenRows: 36 }, heightIn: 60, spreadIn: 24,
    humidityDisease: 'low', diseases: ['Fusarium wilt', 'root-knot nematodes'], pests: ['stink bugs', 'aphids'], yieldLb: { per: '10ft-row', range: [5, 10] },
  },
  {
    id: 'celery', commonName: 'Celery', scientificName: 'Apium graveolens var. dulce', family: API, kind: 'vegetable', lifecycle: 'biennial',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 5, ideal: 6 },
    daysToMaturity: [85, 120], maturityFrom: 'transplant',
    germination: { minSoilF: 40, optimalF: [60, 70], days: [14, 21] },
    sowing: { method: 'transplant', indoorStartWeeks: [12, 10], transplantDays: [7, 21], minSoilF: 50 },
    harvestWindowDays: 30, water: 'high', soil: { pH: [6.0, 7.0], drainage: 'moist' },
    spacingIn: { inRow: 8, betweenRows: 24 }, perSquareFoot: 4, heightIn: 20, spreadIn: 8,
    humidityDisease: 'medium', diseases: ['early blight', 'late blight (Septoria)'], pests: ['aphids', 'carrot rust fly'],
    yieldLb: { per: '10ft-row', range: [10, 15] }, notes: ['Transplants exposed to 10+ days below 50 °F may bolt.'],
  },
  {
    id: 'arugula', commonName: 'Arugula', scientificName: 'Eruca vesicaria subsp. sativa', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [30, 40], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [55, 75], days: [4, 7] },
    sowing: { method: 'direct', directSowDays: [-28, 7], minSoilF: 40, fallDaysBeforeFirstFrost: [50, 30], successionDays: 14 },
    harvestWindowDays: 21, water: 'medium', soil: { pH: [6.0, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 4, betweenRows: 10 }, perSquareFoot: 9, heightIn: 10, spreadIn: 6,
    humidityDisease: 'low', diseases: ['downy mildew'], pests: ['flea beetles'], yieldLb: { per: '10ft-row', range: [2, 4] },
  },
  {
    id: 'bok-choy', commonName: 'Bok choy', scientificName: 'Brassica rapa (Chinensis group)', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'half-hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [45, 60], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 7] },
    sowing: { method: 'either', indoorStartWeeks: [5, 4], transplantDays: [-14, 0], directSowDays: [-21, 0], minSoilF: 45, fallDaysBeforeFirstFrost: [60, 45] },
    harvestWindowDays: 14, water: 'high', soil: { pH: [6.0, 7.5], drainage: 'moist' },
    spacingIn: { inRow: 8, betweenRows: 18 }, perSquareFoot: 4, heightIn: 12, spreadIn: 10,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [5, 10] },
  },
  {
    id: 'mustard-greens', commonName: 'Mustard greens', scientificName: 'Brassica juncea', family: BRA, kind: 'vegetable', lifecycle: 'annual',
    season: 'cool', frost: 'hardy', heat: 'low', sunHours: { min: 4, ideal: 6 },
    daysToMaturity: [30, 45], maturityFrom: 'seed',
    germination: { minSoilF: 40, optimalF: [60, 85], days: [4, 7] },
    sowing: { method: 'direct', directSowDays: [-28, 0], minSoilF: 40, fallDaysBeforeFirstFrost: [60, 40], successionDays: 14 },
    harvestWindowDays: 30, water: 'medium', soil: { pH: [6.0, 7.5], drainage: 'well-drained' },
    spacingIn: { inRow: 6, betweenRows: 15 }, perSquareFoot: 4, heightIn: 18, spreadIn: 10,
    humidityDisease: 'medium', diseases: BRASSICA_DISEASES, pests: BRASSICA_PESTS, yieldLb: { per: '10ft-row', range: [4, 8] },
  },
  {
    id: 'asparagus', commonName: 'Asparagus', scientificName: 'Asparagus officinalis', family: ASP, kind: 'vegetable', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'medium', sunHours: { min: 6, ideal: 8 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0], minSoilF: 50 },
    harvestWindowDays: 42, water: 'medium', soil: { pH: [6.5, 7.5], drainage: 'well-drained', textures: ['sandy', 'loamy'] },
    spacingIn: { inRow: 18, betweenRows: 48 }, heightIn: 60, spreadIn: 24, zones: [3, 8],
    humidityDisease: 'medium', diseases: ['Fusarium crown rot', 'rust'], pests: ['asparagus beetles'],
    yieldLb: { per: '10ft-row', range: [2, 4] }, yearsToBearing: [2, 3],
    notes: ['Plant crowns in a permanent bed; ferny summer growth is 5 ft tall.'],
  },
  {
    id: 'rhubarb', commonName: 'Rhubarb', scientificName: 'Rheum × hybridum', family: POL, kind: 'vegetable', lifecycle: 'perennial',
    season: 'perennial', frost: 'very-hardy', heat: 'low', sunHours: { min: 5, ideal: 6 }, maturityFrom: 'planting',
    sowing: { method: 'plant', directSowDays: [-28, 0] },
    harvestWindowDays: 56, water: 'medium', soil: { pH: [5.5, 7.0], drainage: 'well-drained' },
    spacingIn: { inRow: 36, betweenRows: 48 }, heightIn: 36, spreadIn: 48, zones: [3, 8], chillHours: [500, 1000],
    humidityDisease: 'low', diseases: ['crown rot'], pests: ['rhubarb curculio'],
    yieldLb: { per: 'plant', range: [2, 4] }, yearsToBearing: [2, 2], notes: ['Leaves are toxic; eat only the stalks. Needs cold winters.'],
  },
];
