/**
 * USDA Plant Hardiness Zone (2023 PHZM, produced by PRISM / Oregon State University).
 * Offline first: a compact ZIP→zone table is generated by `pnpm build:zones` (from the frostline
 * dataset, MIT) and bundled. If a ZIP is missing from the bundle, fall back to the keyless static
 * files at phzmapi.org (the same dataset, hosted as static JSON).
 * Resolution is ZIP/ZCTA-level, so confidence is 'medium' — the true PHZM grid is ~800 m.
 */
import { sourced, unavailable, type Layer } from '@homeground/core';
import { type HttpClient, TTL } from './http';

export const PHZM_SOURCE = 'USDA Plant Hardiness Zone Map 2023 (PRISM/OSU)';
const LICENSE =
  'USDA/PRISM PHZM data; ZIP table via frostline (MIT). Not the official USDA map image; see planthardiness.ars.usda.gov.';

export interface HardinessZone {
  /** e.g. "6b" */
  zone: string;
  /** Average annual extreme minimum temperature range, °F, e.g. [-5, 0]. */
  rangeF?: [number, number];
  zip: string;
}

/** Compact bundled table: zip → "6b". Populated at build time; empty until `pnpm build:zones` runs. */
export type ZoneTable = Record<string, string>;

/** Lower bound of the zone's average extreme minimum, °F. Zone 1a = −60 °F, each half-zone is 5 °F. */
export function zoneRangeF(zone: string): [number, number] | undefined {
  const m = /^(\d{1,2})([ab])$/.exec(zone.trim());
  if (!m) return undefined;
  const n = Number(m[1]), half = m[2] === 'b' ? 1 : 0;
  const lo = -60 + ((n - 1) * 2 + half) * 5;
  return [lo, lo + 5];
}

interface PhzmApiResponse {
  zone?: string;
  temperature_range?: string;
}

export async function hardinessZone(http: HttpClient, zip: string | undefined, table: ZoneTable = {}): Promise<Layer<HardinessZone>> {
  if (!zip || !/^\d{5}$/.test(zip)) return unavailable(PHZM_SOURCE, 'No ZIP code for this location.', false);
  const attribution = {
    source: PHZM_SOURCE,
    license: LICENSE,
    resolution: 'ZIP code',
    confidence: 'medium' as const,
    basis: 'reference' as const,
    notes: ['Zone is for the ZIP code; hilltops and frost pockets on your land can differ by half a zone or more.'],
    url: 'https://planthardiness.ars.usda.gov/',
  };
  const bundled = table[zip];
  if (bundled) return sourced({ zone: bundled, rangeF: zoneRangeF(bundled), zip }, attribution);
  try {
    const { data } = await http.json<PhzmApiResponse>(`https://phzmapi.org/${zip}.json`, { ttlMs: TTL.static });
    if (!data.zone) return unavailable(PHZM_SOURCE, `ZIP ${zip} is not in the hardiness dataset.`, false);
    return sourced({ zone: data.zone, rangeF: zoneRangeF(data.zone), zip }, attribution);
  } catch (e) {
    return unavailable(PHZM_SOURCE, `Hardiness lookup failed (${(e as Error).message}).`, true);
  }
}
